"""
ResQAI - Route Model
Optimized delivery routes generated by the Route Optimization Agent.
Stores polylines, waypoints, traffic data, and algorithm metadata.
"""

import enum
import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Boolean, Enum, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import BaseModel

if TYPE_CHECKING:
    from .delivery import Delivery


class RouteAlgorithm(str, enum.Enum):
    """Algorithm used to compute the route."""
    ASTAR = "astar"
    DIJKSTRA = "dijkstra"
    VRP = "vrp"
    TSP = "tsp"
    GENETIC = "genetic"
    OR_TOOLS = "or_tools"
    GOOGLE_DIRECTIONS = "google_directions"
    OPENROUTE = "openroute"
    DYNAMIC = "dynamic"


class RouteStatus(str, enum.Enum):
    COMPUTED = "computed"
    IN_USE = "in_use"
    COMPLETED = "completed"
    REROUTED = "rerouted"
    CANCELLED = "cancelled"


class Route(BaseModel):
    """
    Delivery route record produced by the Route Optimization Agent.
    Stores the encoded polyline, waypoints, and environmental factors
    (traffic, weather) that influenced the route decision.
    """

    __tablename__ = "routes"
    __table_args__ = (
        Index("idx_routes_delivery_id", "delivery_id"),
        Index("idx_routes_status", "status"),
        {"schema": "resqai"},
    )

    delivery_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("resqai.deliveries.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )

    # ---- Route Data ----
    encoded_polyline: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    waypoints: Mapped[Optional[list]] = mapped_column(
        JSONB,
        nullable=True,
        default=list,
        comment="[{lat, lng, label, estimated_arrival, is_pickup, is_delivery}]"
    )
    bounds: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="{north, south, east, west}"
    )

    # ---- Metrics ----
    total_distance_km: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_duration_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    pickup_to_delivery_km: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ---- Algorithm ----
    algorithm: Mapped[RouteAlgorithm] = mapped_column(
        Enum(RouteAlgorithm, name="route_algorithm", schema="resqai"),
        nullable=False,
        default=RouteAlgorithm.OR_TOOLS,
    )
    computation_time_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    alternative_routes: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)
    optimization_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ---- Context at Computation Time ----
    traffic_condition: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    traffic_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    weather_condition: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    weather_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # ---- Flags ----
    is_traffic_aware: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_weather_aware: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_multi_stop: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # ---- Status ----
    status: Mapped[RouteStatus] = mapped_column(
        Enum(RouteStatus, name="route_status", schema="resqai"),
        nullable=False,
        default=RouteStatus.COMPUTED,
    )

    # ---- Relationships ----
    delivery: Mapped["Delivery"] = relationship("Delivery", back_populates="route")
